server:
  port: 5050
  shutdown: graceful
  
spring:
  application:
    name: app-service
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?useSSL=false&allowPublicKeyRetrieval=true
    username: app_server
    password: apppassword
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


logging.level.org.springframework: TRACE